spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cms_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  sql:
    init:
#      mode: always
      mode: never

server:
  port: 8080

logging:
  level:
    root: INFO
    com.epic.cms: DEBUG

# Card Encryption Configuration
cms:
  security:
    encryption:
      key: "a8F3kLm9PqR2sT7vXyZ1w4U6nB8cD0eF" # 16/24/32 characters for AES
      algorithm: "AES"
      transformation: "AES/ECB/PKCS5Padding"

# SpringDoc OpenAPI Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    try-it-out-enabled: true
    operations-sorter: method
    tags-sorter: alpha
    doc-expansion: none
    disable-swagger-default-url: true
    display-request-duration: true
    default-models-expand-depth: 1
    default-model-expand-depth: 1
